import type {
  Service,
  StaffMember,
  Client,
  Appointment,
  RevenueDataPoint,
} from "./types";

/* ─── Services ──────────────────────────────────────────────── */
export const services: Service[] = [
  // Hombre
  {
    id: "h1",
    name: "Corte Clásico",
    description: "Corte tradicional con acabado perfecto y estilo atemporal.",
    price: 20,
    duration: 30,
    category: "hombre",
    icon: "scissors",
    popular: false,
  },
  {
    id: "h2",
    name: "Corte + Barba",
    description: "Combo premium: corte a medida y diseño completo de barba.",
    price: 35,
    duration: 50,
    category: "hombre",
    icon: "scissors",
    popular: true,
  },
  {
    id: "h3",
    name: "Afeitado Tradicional",
    description: "Ritual de afeitado con navaja, paños calientes y aceites premium.",
    price: 25,
    duration: 35,
    category: "hombre",
    icon: "layers",
    popular: false,
  },
  {
    id: "h4",
    name: "Diseño de Barba",
    description: "Perfilado y diseño preciso de barba con definición de líneas.",
    price: 20,
    duration: 25,
    category: "hombre",
    icon: "star",
    popular: false,
  },
  {
    id: "h5",
    name: "Corte Infantil",
    description: "Corte especial para los más pequeños de la casa (hasta 12 años).",
    price: 15,
    duration: 20,
    category: "hombre",
    icon: "heart",
    popular: false,
  },
  {
    id: "h6",
    name: "Tratamiento Capilar",
    description: "Hidratación profunda, keratin o tratamiento anticaída.",
    price: 45,
    duration: 60,
    category: "hombre",
    icon: "sparkles",
    popular: false,
  },
  // Mujer
  {
    id: "m1",
    name: "Corte y Peinado",
    description: "Corte personalizado con blow-dry y peinado de acabado.",
    price: 35,
    duration: 60,
    category: "mujer",
    icon: "scissors",
    popular: false,
  },
  {
    id: "m2",
    name: "Coloración Completa",
    description: "Tinte en color sólido con productos premium sin amoníaco.",
    price: 70,
    duration: 120,
    category: "mujer",
    icon: "palette",
    popular: true,
  },
  {
    id: "m3",
    name: "Mechas / Balayage",
    description: "Técnica de mechas o balayage para un resultado natural y luminoso.",
    price: 90,
    duration: 150,
    category: "mujer",
    icon: "sparkles",
    popular: true,
  },
  {
    id: "m4",
    name: "Tratamiento Keratina",
    description: "Alisado duradero con keratina brasileña. Hasta 3 meses de duración.",
    price: 80,
    duration: 90,
    category: "mujer",
    icon: "star",
    popular: false,
  },
  {
    id: "m5",
    name: "Peinado Especial",
    description: "Peinados elaborados para eventos, bodas, comuniones y celebraciones.",
    price: 55,
    duration: 90,
    category: "mujer",
    icon: "heart",
    popular: false,
  },
  {
    id: "m6",
    name: "Manicura + Pedicura",
    description: "Cuidado completo de uñas con esmaltado semipermanente incluido.",
    price: 40,
    duration: 60,
    category: "mujer",
    icon: "gem",
    popular: false,
  },
];

/* ─── Staff ─────────────────────────────────────────────────── */
export const staff: StaffMember[] = [
  {
    id: "s1",
    name: "Carlos Martínez",
    role: "Master Barber",
    specialties: ["Corte Clásico", "Diseño de Barba", "Afeitado Tradicional"],
    rating: 4.9,
    reviews: 328,
    experience: 12,
    avatar: "https://ui-avatars.com/api/?name=Carlos+Martinez&background=1a1a1a&color=c9a84c&size=200&bold=true&font-size=0.4",
    available: true,
  },
  {
    id: "s2",
    name: "Sofía García",
    role: "Estilista Senior",
    specialties: ["Coloración", "Balayage", "Peinados de Novia"],
    rating: 4.9,
    reviews: 412,
    experience: 9,
    avatar: "https://ui-avatars.com/api/?name=Sofia+Garcia&background=1a1a1a&color=d4728a&size=200&bold=true&font-size=0.4",
    available: true,
  },
  {
    id: "s3",
    name: "Alejandro Ruiz",
    role: "Especialista en Barba",
    specialties: ["Barba artística", "Corte + Barba", "Afeitado al ras"],
    rating: 4.8,
    reviews: 197,
    experience: 7,
    avatar: "https://ui-avatars.com/api/?name=Alejandro+Ruiz&background=1a1a1a&color=c9a84c&size=200&bold=true&font-size=0.4",
    available: true,
  },
  {
    id: "s4",
    name: "Valentina López",
    role: "Colorista & Estilista",
    specialties: ["Keratina", "Mechas", "Corte femenino"],
    rating: 4.9,
    reviews: 286,
    experience: 8,
    avatar: "https://ui-avatars.com/api/?name=Valentina+Lopez&background=1a1a1a&color=d4728a&size=200&bold=true&font-size=0.4",
    available: true,
  },
  {
    id: "s5",
    name: "Marcos Fernández",
    role: "Técnico Capilar",
    specialties: ["Tratamientos capilares", "Diagnóstico", "Hidratación"],
    rating: 4.7,
    reviews: 143,
    experience: 5,
    avatar: "https://ui-avatars.com/api/?name=Marcos+Fernandez&background=1a1a1a&color=c9a84c&size=200&bold=true&font-size=0.4",
    available: false,
  },
];

/* ─── Clients ───────────────────────────────────────────────── */
export const clients: Client[] = [
  { id: "c1", name: "Miguel Ángel Torres", email: "m.torres@gmail.com", phone: "+34 612 345 678", visits: 24, totalSpent: 820, lastVisit: "2026-04-10", vip: true },
  { id: "c2", name: "Laura Sánchez",       email: "laura.s@hotmail.com",  phone: "+34 623 456 789", visits: 18, totalSpent: 1240, lastVisit: "2026-04-12", vip: true },
  { id: "c3", name: "Javier Romero",       email: "j.romero@yahoo.es",    phone: "+34 634 567 890", visits: 32, totalSpent: 640, lastVisit: "2026-04-08", vip: true },
  { id: "c4", name: "Ana Belén Castro",    email: "anabelen@gmail.com",   phone: "+34 645 678 901", visits: 11, totalSpent: 930, lastVisit: "2026-04-14", vip: false },
  { id: "c5", name: "Roberto Giménez",     email: "r.gimenez@outlook.es", phone: "+34 656 789 012", visits: 7,  totalSpent: 175, lastVisit: "2026-04-01", vip: false },
  { id: "c6", name: "Carmen Vidal",        email: "carmen.v@gmail.com",   phone: "+34 667 890 123", visits: 15, totalSpent: 1060, lastVisit: "2026-04-11", vip: true },
  { id: "c7", name: "Diego Morales",       email: "d.morales@gmail.com",  phone: "+34 678 901 234", visits: 41, totalSpent: 820, lastVisit: "2026-04-13", vip: true },
  { id: "c8", name: "Natalia Herrero",     email: "natalia.h@gmail.com",  phone: "+34 689 012 345", visits: 9,  totalSpent: 710, lastVisit: "2026-04-05", vip: false },
  { id: "c9", name: "Pablo Ortega",        email: "p.ortega@gmail.com",   phone: "+34 690 123 456", visits: 5,  totalSpent: 100, lastVisit: "2026-03-28", vip: false },
  { id: "c10", name: "Isabella Martín",    email: "isa.martin@gmail.com", phone: "+34 601 234 567", visits: 22, totalSpent: 1580, lastVisit: "2026-04-15", vip: true },
];

/* ─── Appointments ──────────────────────────────────────────── */
export const appointments: Appointment[] = [
  { id: "a1",  clientName: "Miguel Ángel Torres", clientEmail: "m.torres@gmail.com",  clientPhone: "+34 612 345 678", service: "Corte + Barba",         staffMember: "Carlos Martínez",   date: "2026-04-15", time: "09:00", duration: 50, price: 35, status: "confirmada" },
  { id: "a2",  clientName: "Laura Sánchez",       clientEmail: "laura.s@hotmail.com",  clientPhone: "+34 623 456 789", service: "Balayage",               staffMember: "Sofía García",      date: "2026-04-15", time: "10:00", duration: 150, price: 90, status: "confirmada" },
  { id: "a3",  clientName: "Javier Romero",       clientEmail: "j.romero@yahoo.es",    clientPhone: "+34 634 567 890", service: "Afeitado Tradicional",   staffMember: "Alejandro Ruiz",    date: "2026-04-15", time: "11:00", duration: 35, price: 25, status: "completada" },
  { id: "a4",  clientName: "Ana Belén Castro",    clientEmail: "anabelen@gmail.com",   clientPhone: "+34 645 678 901", service: "Coloración Completa",    staffMember: "Valentina López",   date: "2026-04-15", time: "12:00", duration: 120, price: 70, status: "confirmada" },
  { id: "a5",  clientName: "Roberto Giménez",     clientEmail: "r.gimenez@outlook.es", clientPhone: "+34 656 789 012", service: "Corte Clásico",          staffMember: "Carlos Martínez",   date: "2026-04-15", time: "13:00", duration: 30, price: 20, status: "pendiente" },
  { id: "a6",  clientName: "Carmen Vidal",        clientEmail: "carmen.v@gmail.com",   clientPhone: "+34 667 890 123", service: "Tratamiento Keratina",   staffMember: "Sofía García",      date: "2026-04-15", time: "15:00", duration: 90, price: 80, status: "confirmada" },
  { id: "a7",  clientName: "Diego Morales",       clientEmail: "d.morales@gmail.com",  clientPhone: "+34 678 901 234", service: "Diseño de Barba",        staffMember: "Alejandro Ruiz",    date: "2026-04-15", time: "16:00", duration: 25, price: 20, status: "confirmada" },
  { id: "a8",  clientName: "Natalia Herrero",     clientEmail: "natalia.h@gmail.com",  clientPhone: "+34 689 012 345", service: "Manicura + Pedicura",    staffMember: "Valentina López",   date: "2026-04-15", time: "17:00", duration: 60, price: 40, status: "pendiente" },
  { id: "a9",  clientName: "Pablo Ortega",        clientEmail: "p.ortega@gmail.com",   clientPhone: "+34 690 123 456", service: "Corte Clásico",          staffMember: "Carlos Martínez",   date: "2026-04-16", time: "09:30", duration: 30, price: 20, status: "pendiente" },
  { id: "a10", clientName: "Isabella Martín",     clientEmail: "isa.martin@gmail.com", clientPhone: "+34 601 234 567", service: "Corte y Peinado",        staffMember: "Sofía García",      date: "2026-04-16", time: "10:30", duration: 60, price: 35, status: "confirmada" },
  { id: "a11", clientName: "Miguel Ángel Torres", clientEmail: "m.torres@gmail.com",   clientPhone: "+34 612 345 678", service: "Corte + Barba",         staffMember: "Carlos Martínez",   date: "2026-04-14", time: "11:00", duration: 50, price: 35, status: "completada" },
  { id: "a12", clientName: "Carmen Vidal",        clientEmail: "carmen.v@gmail.com",   clientPhone: "+34 667 890 123", service: "Balayage",               staffMember: "Valentina López",   date: "2026-04-14", time: "14:00", duration: 150, price: 90, status: "completada" },
];

/* ─── Testimonials ──────────────────────────────────────────── */
export const testimonials = [
  {
    id: "t1",
    name: "Miguel Torres",
    role: "Cliente habitual",
    text: "Llevo más de 2 años viniendo a StudioNova y nunca me han decepcionado. Carlos es un maestro con las tijeras. El ambiente es increíble y el servicio, de primera.",
    rating: 5,
    service: "Corte + Barba",
    avatar: "https://ui-avatars.com/api/?name=Miguel+Torres&background=252525&color=c9a84c&size=100&bold=true",
  },
  {
    id: "t2",
    name: "Laura Sánchez",
    role: "Clienta VIP",
    text: "Sofía transformó completamente mi cabello con un balayage increíble. Escucha exactamente lo que quieres y el resultado supera siempre las expectativas. ¡Totalmente recomendada!",
    rating: 5,
    service: "Balayage",
    avatar: "https://ui-avatars.com/api/?name=Laura+Sanchez&background=252525&color=d4728a&size=100&bold=true",
  },
  {
    id: "t3",
    name: "Alejandro García",
    role: "Nuevo cliente",
    text: "El afeitado tradicional con navaja fue una experiencia única. Paños calientes, aceites aromáticos... te sientes en una barbería de lujo. Definitivamente repetiré.",
    rating: 5,
    service: "Afeitado Tradicional",
    avatar: "https://ui-avatars.com/api/?name=Alejandro+Garcia&background=252525&color=c9a84c&size=100&bold=true",
  },
  {
    id: "t4",
    name: "Carmen Martínez",
    role: "Clienta habitual",
    text: "El tratamiento de keratina de Valentina duró más de 3 meses. Mi pelo nunca había estado tan liso y brillante. El precio es justo para la calidad que ofrecen.",
    rating: 5,
    service: "Keratina",
    avatar: "https://ui-avatars.com/api/?name=Carmen+Martinez&background=252525&color=d4728a&size=100&bold=true",
  },
  {
    id: "t5",
    name: "Roberto Fernández",
    role: "Cliente frecuente",
    text: "El mejor sitio para el diseño de barba en Madrid. Alejandro tiene un nivel artístico impresionante. En 25 minutos te deja con una barba perfectamente definida.",
    rating: 5,
    service: "Diseño de Barba",
    avatar: "https://ui-avatars.com/api/?name=Roberto+Fernandez&background=252525&color=c9a84c&size=100&bold=true",
  },
  {
    id: "t6",
    name: "Natalia Herrero",
    role: "Clienta VIP",
    text: "Vine para el peinado de mi boda y quedé maravillada. El equipo entero es profesional, amable y crea un ambiente de lujazo. Mi día especial fue perfecto gracias a ellos.",
    rating: 5,
    service: "Peinado de Novia",
    avatar: "https://ui-avatars.com/api/?name=Natalia+Herrero&background=252525&color=d4728a&size=100&bold=true",
  },
];

/* ─── Revenue data (last 14 days) ───────────────────────────── */
export const revenueData: RevenueDataPoint[] = [
  { date: "02 Abr", revenue: 680,  appointments: 12 },
  { date: "03 Abr", revenue: 920,  appointments: 18 },
  { date: "04 Abr", revenue: 540,  appointments: 10 },
  { date: "05 Abr", revenue: 1100, appointments: 22 },
  { date: "06 Abr", revenue: 850,  appointments: 16 },
  { date: "07 Abr", revenue: 760,  appointments: 14 },
  { date: "08 Abr", revenue: 430,  appointments: 8 },
  { date: "09 Abr", revenue: 980,  appointments: 19 },
  { date: "10 Abr", revenue: 1240, appointments: 24 },
  { date: "11 Abr", revenue: 870,  appointments: 17 },
  { date: "12 Abr", revenue: 1060, appointments: 21 },
  { date: "13 Abr", revenue: 590,  appointments: 11 },
  { date: "14 Abr", revenue: 1350, appointments: 26 },
  { date: "15 Abr", revenue: 940,  appointments: 18 },
];

/* ─── Gallery images ────────────────────────────────────────── */
export const galleryImages = [
  { src: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80", alt: "Barbería de lujo" },
  { src: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=800&q=80", alt: "Interior StudioNova" },
  { src: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=800&q=80", alt: "Corte profesional" },
  { src: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80", alt: "Salón de belleza" },
  { src: "https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=800&q=80", alt: "Peinado artístico" },
  { src: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80", alt: "Tratamiento capilar" },
  { src: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=800&q=80", alt: "Barbería premium" },
  { src: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?auto=format&fit=crop&w=800&q=80", alt: "Estilo masculino" },
];

/* ─── Pricing plans ─────────────────────────────────────────── */
export const pricingPlans = [
  {
    id: "basic",
    name: "Básico",
    price: 0,
    period: "gratis",
    description: "Para probar la plataforma con funciones esenciales.",
    features: [
      "Hasta 50 citas / mes",
      "Perfil de negocio básico",
      "Reservas online",
      "Recordatorios por email",
      "Panel de administración",
    ],
    notIncluded: ["Pagos online", "Estadísticas avanzadas", "Soporte prioritario"],
    cta: "Empezar gratis",
    highlighted: false,
  },
  {
    id: "pro",
    name: "Profesional",
    price: 49,
    period: "mes",
    description: "El plan más popular para negocios en crecimiento.",
    features: [
      "Citas ilimitadas",
      "Perfil premium verificado",
      "Reservas + pagos online",
      "Recordatorios SMS y email",
      "Estadísticas completas",
      "Gestión de equipo",
      "Galería de fotos",
      "Soporte prioritario",
    ],
    notIncluded: ["API personalizada", "White-label"],
    cta: "Probar 14 días gratis",
    highlighted: true,
  },
  {
    id: "elite",
    name: "Elite",
    price: 99,
    period: "mes",
    description: "Para cadenas y negocios que quieren lo mejor.",
    features: [
      "Todo en Profesional",
      "Multi-sede incluida",
      "API personalizada",
      "Branding white-label",
      "Onboarding personalizado",
      "Account manager dedicado",
      "Contratos anuales con descuento",
    ],
    notIncluded: [],
    cta: "Contactar ventas",
    highlighted: false,
  },
];

/* ─── Time slots ────────────────────────────────────────────── */
export const timeSlots = [
  { id: "ts1",  time: "09:00", available: true },
  { id: "ts2",  time: "09:30", available: true },
  { id: "ts3",  time: "10:00", available: false },
  { id: "ts4",  time: "10:30", available: true },
  { id: "ts5",  time: "11:00", available: true },
  { id: "ts6",  time: "11:30", available: false },
  { id: "ts7",  time: "12:00", available: true },
  { id: "ts8",  time: "12:30", available: true },
  { id: "ts9",  time: "13:00", available: false },
  { id: "ts10", time: "13:30", available: true },
  { id: "ts11", time: "16:00", available: true },
  { id: "ts12", time: "16:30", available: true },
  { id: "ts13", time: "17:00", available: false },
  { id: "ts14", time: "17:30", available: true },
  { id: "ts15", time: "18:00", available: true },
  { id: "ts16", time: "18:30", available: true },
  { id: "ts17", time: "19:00", available: false },
  { id: "ts18", time: "19:30", available: true },
];
